name: Code style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Black
        uses: psf/black@stable
