name: Command Line Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Python ${{ matrix.python_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip poetry
          python3 -m poetry install

      - name: Run Tests
        run: |
          python3 -m poetry run pytest tests.py
